language: node_js
node_js:
  - "7"
before_install:
  - openssl aes-256-cbc -K $encrypted_001d217edcb2_key -iv $encrypted_001d217edcb2_iv -in service-account.json.enc -out service-account.json -d
install:
  - npm install -g lerna
  - npm install -g eslint
  - lerna bootstrap
script:
  - ./scripts/test.sh